module.exports = {
  USER_ONLINE: 'USER_ONLINE',
  LOG_IN: 'LOG_IN',
  FRIEND_ONLINE: 'FRIEND_ONLINE',
  SEND_NEW_MESSAGE: 'SEND_NEW_MESSAGE',
  RECEIVE_NEW_MESSAGE: 'RECEIVE_NEW_MESSAGE',
  FRIEND_EMOTION_CHANGE: 'FRIEND_EMOTION_CHANGE'
};
